spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shinshinjiru/config-properties
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    virtual-host: ${RABBITMQ_USERNAME}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
